In [1]:
# 1. Force remove the wrong 'edgar' package and alternatives
%pip uninstall edgar python-edgar sec-api -y

# 2. Install the correct package (it must be 'edgartools')
%pip install edgartools

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping edgar as it is not installed.
WARNING: Skipping python-edgar as it is not installed.
WARNING: Skipping sec-api as it is not installed.

Requirement already satisfied: edgartools in c:\users\jabob\.conda\conda\lib\site-packages (5.31.3)
Requirement already satisfied: beautifulsoup4>=4.10.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.14.3)
Requirement already satisfied: httpx>=0.25.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.28.1)
Requirement already satisfied: httpxthrottlecache>=0.3.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.3.5)
Requirement already satisfied: humanize>=4.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.15.0)
Requirement already satisfied: jinja2>=3.1.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.1.2)
Requirement already satisfied: lxml>=4.4 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (6.1.0)
Requirement already satisfied: nest-asyncio>=1.5.1 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (1.5.6)
Requirement already satisfied: orjson>=3.6.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.11.9)
Requirement already satisfied: pandas>=2.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.0.3)
Requirement already satisfied: pyarrow>=17.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (24.0.0)
Requirement already satisfied: pydantic>=2.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (2.13.3)
Requirement already satisfied: pyrate-limiter>=3.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.1.0)
Requirement already satisfied: rank-bm25>=0.2.1 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.2.2)
Requirement already satisfied: rapidfuzz>=3.5.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.14.5)
Requirement already satisfied: rich>=13.8.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (15.0.0)
Requirement already satisfied: stamina>=24.2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (26.1.0)
Requirement already satisfied: tabulate>=0.9.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.10.0)
Requirement already satisfied: textdistance>=4.5.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.6.3)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.65.0)
Requirement already satisfied: truststore>=0.9.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.10.4)
Requirement already satisfied: unidecode>=1.2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (1.2.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\jabob\.conda\conda\lib\site-packages (from beautifulsoup4>=4.10.0->edgartools) (2.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from beautifulsoup4>=4.10.0->edgartools) (4.15.0)
Requirement already satisfied: anyio in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (4.13.0)
Requirement already satisfied: certifi in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (1.0.9)
Requirement already satisfied: idna in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (3.4)
Requirement already satisfied: h11>=0.16 in c:\users\jabob\.conda\conda\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->edgartools) (0.16.0)
Requirement already satisfied: aiofiles>=24.1.0 in c:\users\jabob\.conda\conda\lib\site-packages (from httpxthrottlecache>=0.3.0->edgartools) (25.1.0)
Requirement already satisfied: filelock>=3.18.0 in c:\users\jabob\.conda\conda\lib\site-packages (from httpxthrottlecache>=0.3.0->edgartools) (3.29.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from jinja2>=3.1.0->edgartools) (2.1.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jabob\.conda\conda\lib\site-packages (from pandas>=2.0.0->edgartools) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jabob\.conda\conda\lib\site-packages (from pandas>=2.0.0->edgartools) (2.8.2)
Requirement already satisfied: tzdata in c:\users\jabob\.conda\conda\lib\site-packages (from pandas>=2.0.0->edgartools) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\jabob\.conda\conda\lib\site-packages (from pydantic>=2.0.0->edgartools) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in c:\users\jabob\.conda\conda\lib\site-packages (from pydantic>=2.0.0->edgartools) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\jabob\.conda\conda\lib\site-packages (from pydantic>=2.0.0->edgartools) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from rich>=13.8.0->edgartools) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\jabob\.conda\conda\lib\site-packages (from rich>=13.8.0->edgartools) (2.15.1)
Requirement already satisfied: tenacity in c:\users\jabob\.conda\conda\lib\site-packages (from stamina>=24.2.0->edgartools) (8.2.2)
Requirement already satisfied: colorama in c:\users\jabob\.conda\conda\lib\site-packages (from tqdm>=4.62.0->edgartools) (0.4.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\jabob\.conda\conda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->edgartools) (0.1.0)
Requirement already satisfied: six>=1.5 in c:\users\jabob\.conda\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->edgartools) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# %pip uninstall edgar -y
# ! pip install edgar

# ! pip install sec-api

from edgar import *
set_identity("Jason Rodriguez jabob2002@gmail.com")
import pandas as pd
import numpy as np

c:\Users\jabob\.conda\conda\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.4' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\jabob\.conda\conda\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
#  test 


amex = Company("AXP")


cik = amex.cik

files = amex.get_filings(form="10-Q").head(10)

print(cik)

4962

In [4]:
apple = Company("AAPL")


apple_cik = amex.cik

files = apple.get_filings(form="10-Q").head(10)

print(cik)

4962

In [5]:
import pandas as pd

df = files.to_pandas()

df.columns = df.columns.str.lower()

time_stamps_columns = ['filing_date', 'reportdate']


quarter_col = 'reportdate'

df[quarter_col] = pd.to_datetime(df[quarter_col])
df['quarter_year'] = (
    df['reportdate'].dt.year.astype(str) 
    + "'Q" 
    + df['reportdate'].dt.quarter.astype(str)
)

df

,accession_number,filing_date,reportdate,acceptancedatetime,act,form,filenumber,items,size,isxbrl,isinlinexbrl,primarydocument,primarydocdescription,quarter_year
0,0000320193-26-000013,2026-05-01,2026-03-28,2026-05-01 10:01:00+00:00,34,10-Q,001-36743,,5809851,1,1,aapl-20260328.htm,10-Q,2026'Q1
1,0000320193-26-000006,2026-01-30,2025-12-27,2026-01-30 11:01:32+00:00,34,10-Q,001-36743,,5191740,1,1,aapl-20251227.htm,10-Q,2025'Q4
2,0000320193-25-000073,2025-08-01,2025-06-28,2025-08-01 10:00:42+00:00,34,10-Q,001-36743,,5304776,1,1,aapl-20250628.htm,10-Q,2025'Q2
3,0000320193-25-000057,2025-05-02,2025-03-29,2025-05-02 10:00:46+00:00,34,10-Q,001-36743,,5299807,1,1,aapl-20250329.htm,10-Q,2025'Q1
4,0000320193-25-000008,2025-01-31,2024-12-28,2025-01-31 11:01:27+00:00,34,10-Q,001-36743,,5150277,1,1,aapl-20241228.htm,10-Q,2024'Q4
5,0000320193-24-000081,2024-08-02,2024-06-29,2024-08-01 22:03:34+00:00,34,10-Q,001-36743,,5372771,1,1,aapl-20240629.htm,10-Q,2024'Q2
6,0000320193-24-000069,2024-05-03,2024-03-30,2024-05-02 22:04:25+00:00,34,10-Q,001-36743,,5284139,1,1,aapl-20240330.htm,10-Q,2024'Q1
7,0000320193-24-000006,2024-02-02,2023-12-30,2024-02-01 23:03:38+00:00,34,10-Q,001-36743,,4984121,1,1,aapl-20231230.htm,10-Q,2023'Q4
8,0000320193-23-000077,2023-08-04,2023-07-01,2023-08-03 22:04:43+00:00,34,10-Q,001-36743,,5939898,1,1,aapl-20230701.htm,10-Q,2023'Q3
9,0000320193-23-000064,2023-05-05,2023-04-01,2023-05-04 22:03:52+00:00,34,10-Q,001-36743,,6314786,1,1,aapl-20230401.htm,10-Q,2023'Q2

In [8]:
def fetching_reportings(ticker):
    all_dfs = []

    ticker_var = Company(ticker)
    ticker_cik = ticker_var.cik
    files = ticker_var.get_filings(form=["10-Q", "10-K"])

    for filing in files:
        try:
            xbrl = filing.xbrl()
            if not xbrl:
                continue
                
            income_statement = xbrl.statements.income_statement()
            if income_statement is None:
                continue

            df = income_statement.to_dataframe()
            df = df[df['abstract'] == False].copy()
            
            date_cols = [col for col in df.columns if col[0].isdigit()]
            df = df[['label'] + date_cols]
            df['label'] = df['label'].str.strip().str.replace(':', '')

            df = df.drop_duplicates(subset='label', keep='first')
            df = df.set_index('label')

            df_T = df.T
            df_T.index.name = 'period'
            df_T = df_T.reset_index()
            
            df_T['date'] = pd.to_datetime(df_T['period'].str.extract(r'(\d{4}-\d{2}-\d{2})')[0])
            df_T['period_type'] = df_T['period'].str.extract(r'\((\w+)\)')[0]

            # ---- CHANGE IS HERE ----
            df_T['period_type'] = df_T['period_type'].fillna(
                'Q4' if filing.form == '10-K' else 'SKIP'
            )
            # ------------------------

            df_T = df_T[df_T['period_type'].isin(['Q1', 'Q2', 'Q3', 'Q4'])]
            df_T = df_T.drop(columns=['period', 'period_type']).set_index('date')
            df_T = df_T.apply(pd.to_numeric, errors='coerce')
            
            all_dfs.append(df_T)

        except Exception as e:
            print(f"Failed processing {filing.company} ({filing.filing_date}): {e}")

    df_final = pd.concat(all_dfs)
    df_final['ticker'] = ticker
    df_final = df_final.loc[:, ~df_final.columns.duplicated(keep='first')]
    df_final = df_final[~df_final.index.duplicated(keep='first')]
    df_final = df_final.sort_index()

    df_final.columns = df_final.columns.str.lower().str.replace(' ', '_')
    return df_final

def calculating_margins(data): 
    df_margins = None 
    
    try:
        margins = ['net_sales', 'gross_margin', 'net_income']
        
        if set(margins).issubset(data.columns):
            
            df_margins = data[margins].copy()

            df_margins['gross_margin_rate'] = (df_margins['gross_margin'] / df_margins['net_sales']) * 100
            df_margins['net_margin_rate'] = (df_margins['net_income'] / df_margins['net_sales']) * 100

            df_margins.dropna(axis=0, inplace=True)
            
            df_margins['bps_difference'] = (df_margins['gross_margin_rate'] - df_margins['net_margin_rate']) 
            df_margins['dollar_difference'] = df_margins['gross_margin'] - df_margins['net_income'] 
        else:
            print("Yikes. One or more required columns are missing from the DataFrame.") 
            
    # Catching generic Exceptions ensures you see math/key errors, not just NameErrors
    except Exception as e:
        print(f"Error during calculation: {e}")

    return df_margins

In [10]:
fetching_reportings('WMT')

Filing(company='Walmart Inc.', cik=104169, form='10-Q/A', filing_date='2013-10-21', accession_no='0000104169-13-000039')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2009-06-05', accession_no='0000104169-09-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2009-04-01', accession_no='0000104169-09-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2008-12-09', accession_no='0001193125-08-250391')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2008-09-04', accession_no='0000104169-08-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2008-06-09', accession_no='0001193125-08-130418')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2008-03-31', accession_no='0001193125-08-071085')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2007-11-29', accession_no='0000104169-07-000010')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2007-09-10', accession_no='0001193125-07-198266')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2007-06-01', accession_no='0001193125-07-128008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2007-03-27', accession_no='0001193125-07-065603')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2006-11-30', accession_no='0000104169-06-000015')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2006-08-30', accession_no='0000104169-06-000012')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2006-06-02', accession_no='0000104169-06-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2006-03-29', accession_no='0001193125-06-066792')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2005-12-02', accession_no='0000104169-05-000019')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2005-08-31', accession_no='0000104169-05-000015')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2005-06-03', accession_no='0000104169-05-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2005-03-31', accession_no='0001193125-05-066992')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2004-12-03', accession_no='0001193125-04-207402')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2004-09-03', accession_no='0001193125-04-152109')

Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2004-08-26', accession_no='0001193125-04-147373')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2004-08-26', accession_no='0001193125-04-147373')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2004-06-04', accession_no='0001193125-04-098967')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2004-04-09', accession_no='0001193125-04-059900')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2003-12-11', accession_no='0000104169-03-000021')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2003-09-10', accession_no='0000104169-03-000017')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2003-06-09', accession_no='0000104169-03-000007')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2003-04-15', accession_no='0000104169-03-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2002-12-06', accession_no='0000104169-02-000026')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2002-09-11', accession_no='0000104169-02-000018')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2002-06-10', accession_no='0000104169-02-000009')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2002-04-15', accession_no='0000104169-02-000004')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2001-11-29', accession_no='0000104169-01-500023')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2001-09-04', accession_no='0000104169-01-500019')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2001-06-05', accession_no='0000104169-01-500009')

Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2001-04-17', accession_no='0001021408-01-500157')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2001-04-17', accession_no='0001021408-01-500157')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2001-04-10', accession_no='0001021408-01-500118')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2000-11-30', accession_no='0000104169-00-000010')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2000-08-25', accession_no='0000104169-00-000009')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2000-06-08', accession_no='0000104169-00-000004')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2000-04-17', accession_no='0000104169-00-000002')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1999-12-15', accession_no='0000104169-99-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1999-09-10', accession_no='0000104169-99-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1999-06-07', accession_no='0000104169-99-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1999-04-19', accession_no='0000104169-99-000002')

Filing(company='Walmart Inc.', cik=104169, form='10-Q/A', filing_date='1998-12-23', accession_no='0000104169-98-000010')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q/A', filing_date='1998-12-23', accession_no='0000104169-98-000010')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1998-12-14', accession_no='0000104169-98-000009')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1998-09-14', accession_no='0000104169-98-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1998-06-15', accession_no='0000104169-98-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1998-04-23', accession_no='0000104169-98-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1997-12-10', accession_no='0000104169-97-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1997-09-09', accession_no='0000104169-97-000007')

Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='1997-06-20', accession_no='0000104169-97-000005')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='1997-06-20', accession_no='0000104169-97-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1997-06-10', accession_no='0000104169-97-000004')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1997-04-21', accession_no='0000104169-97-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1996-12-12', accession_no='0000104169-96-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1996-09-10', accession_no='0000104169-96-000007')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1996-06-12', accession_no='0000104169-96-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1996-04-23', accession_no='0000104169-96-000002')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1995-12-05', accession_no='0000104169-95-000007')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1995-09-11', accession_no='0000104169-95-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1995-06-09', accession_no='0000104169-95-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1995-04-27', accession_no='0000104169-95-000004')

label,net_sales,operating_segments_-_walmart u.s.,operating_segments_-_walmart_international,operating_segments_-_sam's club_u.s.,grocery_-_walmart u.s.,general_merchandise_-_walmart u.s.,health_and_wellness_-_walmart u.s.,other_-_walmart u.s.,walmart u.s.,e_commerce_-_walmart u.s.,...,basic_income_per_share_from_continuing_operations_attributable_to_walmart,basic_income_per_share_from_discontinued_operations_attributable_to_walmart,basic_net_income_per_share_attributable_to_walmart,diluted_income_per_share_from_continuing_operations_attributable_to_walmart,diluted_income_(loss)_per_share_from_discontinued_operations_attributable_to_walmart,diluted_net_income_per_share_attributable_to_walmart,dividends_per_share,basic_(loss)_income_per_share_from_discontinued_operations_attributable_to_walmart,diluted_income_per_share_from_discontinued_operations_attributable_to_walmart,ticker
date,,,,,,,,,,,,,,,,,,,,,
2008-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.86,NaN,0.87,0.86,NaN,0.87,0.0,0.01,0.01,WMT
2008-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.77,0.03,0.80,0.77,0.03,0.80,0.0,NaN,NaN,WMT
2009-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2009-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2009-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2010-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2010-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2010-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2011-04-30,1.034150e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2011-07-31,1.086380e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2011-10-31,1.095160e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2012-04-30,1.122640e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2012-07-31,1.135200e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2012-10-31,1.130770e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2013-04-30,1.133130e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2013-07-31,1.161010e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2013-10-31,1.148760e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2014-04-30,1.141670e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2014-07-31,1.193360e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2014-10-31,1.180760e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2015-04-30,1.140020e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2015-07-31,1.193300e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2015-10-31,1.165980e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2016-04-30,1.149860e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2016-07-31,1.194050e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2016-10-31,1.171760e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2017-04-30,1.165260e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2017-07-31,1.219490e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2017-10-31,1.221360e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2018-04-30,1.216300e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2018-07-31,1.270590e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2018-10-31,1.238970e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2019-04-30,1.229490e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2019-07-31,1.293880e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2019-10-31,1.269810e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2020-04-30,1.336720e+11,NaN,8.060000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2020-07-31,1.368240e+11,NaN,8.120000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2020-10-31,1.337520e+11,NaN,1.078000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2021-04-30,1.371590e+11,NaN,1.194000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2021-07-31,1.398710e+11,NaN,8.610000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2021-10-31,1.392070e+11,NaN,8.710000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2022-04-30,1.402880e+11,NaN,7.720000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2022-07-31,1.513810e+11,NaN,1.043000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2022-10-31,1.514690e+11,NaN,8.610000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2023-04-30,1.510040e+11,NaN,1.164000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2023-07-31,1.602800e+11,NaN,1.190000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2023-10-31,1.594390e+11,NaN,1.117000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2024-04-30,1.599380e+11,NaN,2.983300e+10,2.143500e+10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2024-07-31,1.677670e+11,NaN,2.956700e+10,2.285300e+10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2024-10-31,1.680030e+11,NaN,3.027700e+10,2.285100e+10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2025-04-30,1.639810e+11,NaN,2.975400e+10,2.206400e+10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2025-07-31,1.757500e+11,NaN,3.120100e+10,2.363800e+10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT
2025-10-31,1.777690e+11,NaN,3.354100e+10,2.355000e+10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WMT

In [14]:
tickers = ['AAPL', 'nvda', 'googl', 'wmt', 'dis', 'v', 'acn', 'cof', 'ko']
tickers = [ticker.upper() for ticker in tickers]

all_raw_financials = []
all_calculated_margins = []

for ticker in tickers:
    print(f"Processing {ticker}...")
    financial_reports = fetching_reportings(ticker)
    
    if not financial_reports.empty:
        all_raw_financials.append(financial_reports)
        
        margins_for_company = calculating_margins(financial_reports)
        if margins_for_company is not None:
            # Tagging the dataframe so you know which company it belongs to
            margins_for_company['ticker'] = ticker
            all_calculated_margins.append(margins_for_company)

# Combine everything into clean master DataFrames if needed
if all_calculated_margins:
    df_margins_final = pd.concat(all_calculated_margins)
    print("\nProcessing complete! Sample data:")
    print(df_margins_final.head())

Processing AAPL...

Filing(company='Apple Inc.', cik=320193, form='10-K/A', filing_date='2010-01-25', accession_no='0001193125-10-012091')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`


Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='2009-04-27', accession_no='0001193125-09-087629')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='2009-04-27', accession_no='0001193125-09-087629')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2009-04-23', accession_no='0001193125-09-085781')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2009-01-23', accession_no='0001193125-09-009937')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2008-11-05', accession_no='0001193125-08-224958')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2008-07-23', accession_no='0001193125-08-156421')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2008-05-01', accession_no='0001193125-08-097759')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2008-02-01', accession_no='0001193125-08-017426')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2007-11-15', accession_no='0001047469-07-009340')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2007-08-08', accession_no='0001104659-07-059873')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2007-05-10', accession_no='0001104659-07-037745')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2007-02-02', accession_no='0001104659-07-006648')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2006-12-29', accession_no='0001104659-06-084288')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2006-12-29', accession_no='0001104659-06-084286')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2006-05-05', accession_no='0001104659-06-031303')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2006-02-03', accession_no='0001104659-06-005910')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2005-12-01', accession_no='0001104659-05-058421')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2005-08-03', accession_no='0001104659-05-035792')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2005-05-04', accession_no='0001104659-05-020421')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2005-02-01', accession_no='0001104659-05-003520')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2004-12-03', accession_no='0001047469-04-035975')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2004-08-05', accession_no='0001104659-04-022384')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2004-05-06', accession_no='0001104659-04-013021')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2004-02-10', accession_no='0001104659-04-003080')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2003-12-19', accession_no='0001047469-03-041604')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2003-08-12', accession_no='0001104659-03-017766')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2003-05-13', accession_no='0001104659-03-009489')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2003-02-10', accession_no='0001047469-03-004566')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2002-12-19', accession_no='0001047469-02-007674')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2002-08-09', accession_no='0000912057-02-030796')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2002-05-14', accession_no='0000912057-02-020280')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2002-02-11', accession_no='0000912057-02-004945')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2001-08-13', accession_no='0000912057-01-528148')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2001-05-14', accession_no='0000912057-01-515409')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2001-02-12', accession_no='0000912057-01-004642')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2000-12-14', accession_no='0000912057-00-053623')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2000-07-31', accession_no='0000912057-00-033901')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2000-05-11', accession_no='0000912057-00-023442')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2000-02-01', accession_no='0000912057-00-003201')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1999-12-22', accession_no='0000912057-99-010244')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1999-08-06', accession_no='0000320193-99-000009')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1999-05-11', accession_no='0000320193-99-000004')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1999-02-08', accession_no='0000320193-99-000002')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1998-08-10', accession_no='0000320193-98-000008')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1998-05-11', accession_no='0000320193-98-000006')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1998-02-09', accession_no='0000320193-98-000003')

Filing(company='Apple Inc.', cik=320193, form='10-K/A', filing_date='1998-01-23', accession_no='0001047469-98-001822')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K/A', filing_date='1998-01-23', accession_no='0001047469-98-001822')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1997-12-05', accession_no='0001047469-97-006960')

Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='1997-10-07', accession_no='0000320193-97-000021')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='1997-10-07', accession_no='0000320193-97-000021')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1997-08-11', accession_no='0000320193-97-000014')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1997-05-12', accession_no='0000320193-97-000011')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1997-02-10', accession_no='0000320193-97-000002')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1996-12-19', accession_no='0000320193-96-000023')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1996-08-12', accession_no='0000320193-96-000018')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1996-05-13', accession_no='0000320193-96-000011')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1996-02-12', accession_no='0000320193-96-000002')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1995-12-19', accession_no='0000320193-95-000016')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1995-08-11', accession_no='0000320193-95-000011')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1995-05-15', accession_no='0000320193-95-000008')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1995-02-09', accession_no='0000320193-95-000003')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1994-12-13', accession_no='0000320193-94-000016')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1994-08-12', accession_no='0000320193-94-000013')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1994-01-26', accession_no='0000320193-94-000002')

Processing NVDA...

No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2009-05-20', accession_no='0001045810-09-000017')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2009-03-13', accession_no='0001045810-09-000013')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2008-12-02', accession_no='0001045810-08-000030')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2008-08-21', accession_no='0001045810-08-000020')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2008-05-22', accession_no='0001045810-08-000016')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2008-03-21', accession_no='0001045810-08-000011')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2007-11-21', accession_no='0001045810-07-000053')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2007-08-22', accession_no='0001045810-07-000045')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2007-05-24', accession_no='0001045810-07-000019')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2007-03-16', accession_no='0001045810-07-000008')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2006-12-07', accession_no='0001045810-06-000035')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2006-11-29', accession_no='0001193125-06-243229')

Filing(company='NVIDIA CORP', cik=1045810, form='10-Q/A', filing_date='2006-11-29', accession_no='0001193125-06-243226')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q/A', filing_date='2006-11-29', accession_no='0001193125-06-243226')

Filing(company='NVIDIA CORP', cik=1045810, form='10-K/A', filing_date='2006-11-29', accession_no='0001193125-06-243224')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K/A', filing_date='2006-11-29', accession_no='0001193125-06-243224')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2006-05-31', accession_no='0001045810-06-000023')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2006-03-16', accession_no='0001045810-06-000014')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2005-11-23', accession_no='0001045810-05-000028')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2005-08-25', accession_no='0001045810-05-000024')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2005-06-02', accession_no='0001045810-05-000020')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2005-03-22', accession_no='0001045810-05-000008')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2004-11-22', accession_no='0001045810-04-000034')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2004-08-19', accession_no='0001045810-04-000023')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2004-05-20', accession_no='0001045810-04-000015')

Filing(company='NVIDIA CORP', cik=1045810, form='10-K/A', filing_date='2004-05-20', accession_no='0001045810-04-000014')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K/A', filing_date='2004-05-20', accession_no='0001045810-04-000014')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2004-03-29', accession_no='0001045810-04-000007')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2003-11-21', accession_no='0001045810-03-000010')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2003-09-09', accession_no='0001193125-03-047111')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2003-05-22', accession_no='0001012870-03-002787')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2003-04-25', accession_no='0001045969-03-001196')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2002-12-10', accession_no='0001012870-02-004623')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2002-09-10', accession_no='0001012870-02-003728')

Filing(company='NVIDIA CORP', cik=1045810, form='10-Q/A', filing_date='2002-07-03', accession_no='0001012870-02-002921')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q/A', filing_date='2002-07-03', accession_no='0001012870-02-002921')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2002-06-10', accession_no='0001012870-02-002660')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-K', filing_date='2002-05-14', accession_no='0001012870-02-002262')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2001-11-23', accession_no='0001012870-01-502932')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2001-09-10', accession_no='0001012870-01-501827')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2001-06-12', accession_no='0001012870-01-501180')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2000-12-08', accession_no='0001012870-00-006127')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2000-09-13', accession_no='0001012870-00-004766')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='2000-06-14', accession_no='0001012870-00-003358')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='1999-12-10', accession_no='0001012870-99-004592')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='1999-09-10', accession_no='0000898430-99-003541')
No XBRL attachments found in filing Filing(company='NVIDIA CORP', cik=1045810, form='10-Q', filing_date='1999-06-15', accession_no='0001012870-99-001954')

Yikes. One or more required columns are missing from the DataFrame.
Processing GOOGL...

Filing(company='Alphabet Inc.', cik=1652044, form='10-K/A', filing_date='2019-02-06', accession_no='0001193125-19-028757')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Alphabet Inc.', cik=1652044, form='10-K/A', filing_date='2019-02-06', accession_no='0001193125-19-028757')

Filing(company='Alphabet Inc.', cik=1652044, form='10-K/A', filing_date='2016-03-29', accession_no='0001193125-16-520367')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Alphabet Inc.', cik=1652044, form='10-K/A', filing_date='2016-03-29', accession_no='0001193125-16-520367')

Yikes. One or more required columns are missing from the DataFrame.
Processing WMT...

Filing(company='Walmart Inc.', cik=104169, form='10-Q/A', filing_date='2013-10-21', accession_no='0000104169-13-000039')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2009-06-05', accession_no='0000104169-09-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2009-04-01', accession_no='0000104169-09-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2008-12-09', accession_no='0001193125-08-250391')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2008-09-04', accession_no='0000104169-08-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2008-06-09', accession_no='0001193125-08-130418')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2008-03-31', accession_no='0001193125-08-071085')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2007-11-29', accession_no='0000104169-07-000010')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2007-09-10', accession_no='0001193125-07-198266')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2007-06-01', accession_no='0001193125-07-128008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2007-03-27', accession_no='0001193125-07-065603')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2006-11-30', accession_no='0000104169-06-000015')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2006-08-30', accession_no='0000104169-06-000012')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2006-06-02', accession_no='0000104169-06-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2006-03-29', accession_no='0001193125-06-066792')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2005-12-02', accession_no='0000104169-05-000019')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2005-08-31', accession_no='0000104169-05-000015')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2005-06-03', accession_no='0000104169-05-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2005-03-31', accession_no='0001193125-05-066992')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2004-12-03', accession_no='0001193125-04-207402')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2004-09-03', accession_no='0001193125-04-152109')

Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2004-08-26', accession_no='0001193125-04-147373')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2004-08-26', accession_no='0001193125-04-147373')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2004-06-04', accession_no='0001193125-04-098967')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2004-04-09', accession_no='0001193125-04-059900')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2003-12-11', accession_no='0000104169-03-000021')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2003-09-10', accession_no='0000104169-03-000017')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2003-06-09', accession_no='0000104169-03-000007')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2003-04-15', accession_no='0000104169-03-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2002-12-06', accession_no='0000104169-02-000026')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2002-09-11', accession_no='0000104169-02-000018')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2002-06-10', accession_no='0000104169-02-000009')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2002-04-15', accession_no='0000104169-02-000004')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2001-11-29', accession_no='0000104169-01-500023')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2001-09-04', accession_no='0000104169-01-500019')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2001-06-05', accession_no='0000104169-01-500009')

Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2001-04-17', accession_no='0001021408-01-500157')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='2001-04-17', accession_no='0001021408-01-500157')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2001-04-10', accession_no='0001021408-01-500118')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2000-11-30', accession_no='0000104169-00-000010')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2000-08-25', accession_no='0000104169-00-000009')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='2000-06-08', accession_no='0000104169-00-000004')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='2000-04-17', accession_no='0000104169-00-000002')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1999-12-15', accession_no='0000104169-99-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1999-09-10', accession_no='0000104169-99-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1999-06-07', accession_no='0000104169-99-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1999-04-19', accession_no='0000104169-99-000002')

Filing(company='Walmart Inc.', cik=104169, form='10-Q/A', filing_date='1998-12-23', accession_no='0000104169-98-000010')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q/A', filing_date='1998-12-23', accession_no='0000104169-98-000010')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1998-12-14', accession_no='0000104169-98-000009')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1998-09-14', accession_no='0000104169-98-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1998-06-15', accession_no='0000104169-98-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1998-04-23', accession_no='0000104169-98-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1997-12-10', accession_no='0000104169-97-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1997-09-09', accession_no='0000104169-97-000007')

Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='1997-06-20', accession_no='0000104169-97-000005')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K/A', filing_date='1997-06-20', accession_no='0000104169-97-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1997-06-10', accession_no='0000104169-97-000004')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1997-04-21', accession_no='0000104169-97-000003')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1996-12-12', accession_no='0000104169-96-000008')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1996-09-10', accession_no='0000104169-96-000007')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1996-06-12', accession_no='0000104169-96-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1996-04-23', accession_no='0000104169-96-000002')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1995-12-05', accession_no='0000104169-95-000007')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1995-09-11', accession_no='0000104169-95-000006')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-Q', filing_date='1995-06-09', accession_no='0000104169-95-000005')
No XBRL attachments found in filing Filing(company='Walmart Inc.', cik=104169, form='10-K', filing_date='1995-04-27', accession_no='0000104169-95-000004')

Yikes. One or more required columns are missing from the DataFrame.
Processing DIS...

Filing(company='Walt Disney Co', cik=1744489, form='10-K/A', filing_date='2024-01-24', accession_no='0001744489-24-000064')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

Failed to resolve IncomeStatement for WALT DISNEY CO/ (CIK: Unknown, Period: 2023-09-30). No matching statements found. No statements available. No statements available in XBRL data

Filing(company='Walt Disney Co', cik=1744489, form='10-K/A', filing_date='2023-01-24', accession_no='0001193125-23-014219')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

Failed to resolve IncomeStatement for WALT DISNEY CO/ (CIK: Unknown, Period: 2022-10-01). No matching statements found. No statements available. No statements available in XBRL data

Yikes. One or more required columns are missing from the DataFrame.
Processing V...
Failed processing VISA INC. (2009-11-20): 'abstract'

No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-Q', filing_date='2009-05-06', accession_no='0001193125-09-100928')
No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-Q', filing_date='2009-02-09', accession_no='0001193125-09-022518')

Failed processing VISA INC. (2009-07-30): 'abstract'

No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-K', filing_date='2008-11-21', accession_no='0001193125-08-240384')
No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-Q', filing_date='2008-08-13', accession_no='0001193125-08-176170')
No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-Q', filing_date='2008-05-13', accession_no='0001193125-08-113141')

Filing(company='VISA INC.', cik=1403161, form='10-K/A', filing_date='2008-02-25', accession_no='0001193125-08-036840')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-K/A', filing_date='2008-02-25', accession_no='0001193125-08-036840')

Filing(company='VISA INC.', cik=1403161, form='10-Q/A', filing_date='2008-02-13', accession_no='0001193125-08-029437')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-Q/A', filing_date='2008-02-13', accession_no='0001193125-08-029437')

Filing(company='VISA INC.', cik=1403161, form='10-K/A', filing_date='2008-02-04', accession_no='0001193125-08-019268')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-K/A', filing_date='2008-02-04', accession_no='0001193125-08-019268')
No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-Q', filing_date='2008-02-04', accession_no='0001193125-08-019208')
No XBRL attachments found in filing Filing(company='VISA INC.', cik=1403161, form='10-K', filing_date='2007-12-21', accession_no='0001193125-07-270394')

Yikes. One or more required columns are missing from the DataFrame.
Processing ACN...

Filing(company='Accenture plc', cik=1467373, form='10-K/A', filing_date='2012-11-08', accession_no='0001467373-12-000189')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Accenture plc', cik=1467373, form='10-K/A', filing_date='2012-11-08', accession_no='0001467373-12-000189')
No XBRL attachments found in filing Filing(company='Accenture plc', cik=1467373, form='10-K', filing_date='2009-10-19', accession_no='0001193125-09-209671')

Yikes. One or more required columns are missing from the DataFrame.
Processing COF...

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2011-03-07', accession_no='0001140361-11-014724')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2011-03-01', accession_no='0001140361-11-012916')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2009-05-08', accession_no='0001193125-09-105327')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2009-02-26', accession_no='0001193125-09-039271')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2008-11-10', accession_no='0001193125-08-230314')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2008-08-08', accession_no='0001193125-08-171940')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2008-05-09', accession_no='0001193125-08-108143')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2008-02-29', accession_no='0001193125-08-043757')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2007-11-09', accession_no='0001193125-07-242365')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2007-11-09', accession_no='0001193125-07-242365')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2007-11-08', accession_no='0001193125-07-240532')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2007-08-09', accession_no='0001193125-07-177408')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2007-05-09', accession_no='0001193125-07-108326')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2007-03-01', accession_no='0001193125-07-044343')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2006-11-03', accession_no='0001193125-06-223783')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2006-08-07', accession_no='0001193125-06-163869')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2006-05-04', accession_no='0001193125-06-098770')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2006-04-12', accession_no='0001193125-06-077976')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2006-04-12', accession_no='0001193125-06-077976')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2006-04-12', accession_no='0001193125-06-077972')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2006-04-12', accession_no='0001193125-06-077972')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2006-04-12', accession_no='0001193125-06-077967')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2006-04-12', accession_no='0001193125-06-077967')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2006-04-12', accession_no='0001193125-06-077964')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2006-04-12', accession_no='0001193125-06-077964')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2006-04-12', accession_no='0001193125-06-077955')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q/A', filing_date='2006-04-12', accession_no='0001193125-06-077955')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2006-03-02', accession_no='0001193125-06-044064')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2005-11-02', accession_no='0001193125-05-213367')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2005-08-04', accession_no='0001193125-05-157924')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2005-05-03', accession_no='0001193125-05-094067')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2005-03-09', accession_no='0001193125-05-045269')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2004-11-01', accession_no='0001193125-04-182855')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2004-08-05', accession_no='0001193125-04-132739')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2004-05-07', accession_no='0001193125-04-081670')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2004-03-05', accession_no='0001193125-04-035097')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2003-11-10', accession_no='0000950133-03-003779')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2003-08-11', accession_no='0000950133-03-002782')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2003-05-14', accession_no='0000950133-03-001810')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2003-03-17', accession_no='0000950133-03-000793')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2002-11-14', accession_no='0000950133-02-003815')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2002-08-14', accession_no='0000950133-02-002922')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2002-08-14', accession_no='0000950133-02-002922')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2002-08-13', accession_no='0000950133-02-002914')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2002-05-15', accession_no='0000927628-02-000002')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2002-03-22', accession_no='0000928385-02-000920')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2001-11-14', accession_no='0000927628-01-500041')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2001-08-14', accession_no='0000927628-01-500010')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2001-05-11', accession_no='0000928385-01-500803')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2001-03-29', accession_no='0000928385-01-500145')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2000-11-08', accession_no='0000927628-00-000021')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2000-08-14', accession_no='0000927628-00-000014')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='2000-05-15', accession_no='0000927628-00-000004')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2000-03-23', accession_no='0000928385-00-000822')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2000-03-23', accession_no='0000928385-00-000822')

Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2000-03-22', accession_no='0000928385-00-000814')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K/A', filing_date='2000-03-22', accession_no='0000928385-00-000814')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='2000-03-21', accession_no='0000928385-00-000798')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1999-11-15', accession_no='0000927628-99-000012')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1999-08-10', accession_no='0000927628-99-000006')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1999-05-17', accession_no='0000922869-99-000013')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='1999-03-26', accession_no='0000928385-99-000952')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1998-11-13', accession_no='0000922869-98-000020')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1998-08-14', accession_no='0000922869-98-000013')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1998-05-15', accession_no='0000927628-98-000003')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='1998-03-18', accession_no='0000928385-98-000498')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1997-11-14', accession_no='0000928385-97-001906')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1997-08-14', accession_no='0000928385-97-001360')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1997-05-14', accession_no='0000950133-97-001879')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-K', filing_date='1997-03-27', accession_no='0000950133-97-001012')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1996-11-14', accession_no='0000950133-96-002565')
No XBRL attachments found in filing Filing(company='CAPITAL ONE FINANCIAL CORP', cik=927628, form='10-Q', filing_date='1996-08-14', accession_no='0000950133-96-001612')

Yikes. One or more required columns are missing from the DataFrame.
Processing KO...

Filing(company='COCA COLA CO', cik=21344, form='10-Q/A', filing_date='2024-05-30', accession_no='0000021344-24-000019')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

Failed to resolve IncomeStatement for COCA COLA CO (CIK: Unknown, Period: 2024-03-29). No matching statements found. No statements available. No statements available in XBRL data

Filing(company='COCA COLA CO', cik=21344, form='10-Q/A', filing_date='2014-04-30', accession_no='0000021344-14-000018')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q/A', filing_date='2014-04-30', accession_no='0000021344-14-000018')

Filing(company='COCA COLA CO', cik=21344, form='10-Q/A', filing_date='2009-10-29', accession_no='0001047469-09-009321')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2009-10-29', accession_no='0001047469-09-009286')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2009-04-30', accession_no='0001047469-09-004778')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2009-02-26', accession_no='0001047469-09-001875')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2008-10-23', accession_no='0001047469-08-011110')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2008-07-24', accession_no='0001047469-08-008358')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2008-04-25', accession_no='0001047469-08-005195')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2008-02-28', accession_no='0001193125-08-041768')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2007-10-24', accession_no='0001047469-07-007893')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2007-07-26', accession_no='0001047469-07-005866')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2007-04-26', accession_no='0001047469-07-003223')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2007-02-21', accession_no='0001047469-07-001328')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2006-10-26', accession_no='0001047469-06-013139')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2006-07-27', accession_no='0001104659-06-049246')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2006-04-27', accession_no='0001104659-06-028278')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2006-02-28', accession_no='0001047469-06-002588')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2005-10-27', accession_no='0001104659-05-050698')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2005-08-01', accession_no='0001104659-05-035430')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2005-04-28', accession_no='0001047469-05-011762')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2005-03-04', accession_no='0001047469-05-005411')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2004-10-28', accession_no='0001047469-04-032333')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2004-08-05', accession_no='0001047469-04-025463')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2004-04-29', accession_no='0001047469-04-014222')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2004-02-27', accession_no='0001047469-04-005840')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2003-10-27', accession_no='0000021344-03-000157')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2003-08-13', accession_no='0000021344-03-000111')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2003-04-25', accession_no='0000021344-03-000055')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2003-03-26', accession_no='0000021344-03-000031')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2002-11-13', accession_no='0000021344-02-000059')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2002-08-13', accession_no='0000021344-02-000027')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2002-05-10', accession_no='0000021344-02-000017')

Filing(company='COCA COLA CO', cik=21344, form='10-K/A', filing_date='2002-03-13', accession_no='0000021344-02-000013')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K/A', filing_date='2002-03-13', accession_no='0000021344-02-000013')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2002-03-11', accession_no='0000021344-02-000011')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2001-11-13', accession_no='0000021344-01-500040')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2001-08-14', accession_no='0000021344-01-500025')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2001-05-01', accession_no='0000021344-01-500011')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2001-03-07', accession_no='0000021344-01-000005')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2000-10-27', accession_no='0000021344-00-000027')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2000-07-27', accession_no='0000021344-00-000024')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='2000-05-11', accession_no='0000021344-00-000014')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='2000-03-09', accession_no='0000021344-00-000009')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1999-11-03', accession_no='0000021344-99-000026')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1999-08-12', accession_no='0000021344-99-000015')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1999-05-12', accession_no='0000021344-99-000009')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='1999-03-29', accession_no='0000021344-99-000005')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1998-11-12', accession_no='0000021344-98-000016')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1998-08-14', accession_no='0000021344-98-000010')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1998-05-12', accession_no='0000021344-98-000007')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='1998-03-09', accession_no='0000021344-98-000004')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1997-11-13', accession_no='0000021344-97-000034')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1997-08-14', accession_no='0000021344-97-000027')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1997-05-13', accession_no='0000021344-97-000019')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1996-11-14', accession_no='0000021344-96-000026')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1996-08-13', accession_no='0000021344-96-000015')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1996-05-10', accession_no='0000021344-96-000012')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1995-11-13', accession_no='0000021344-95-000041')

Filing(company='COCA COLA CO', cik=21344, form='10-Q/A', filing_date='1995-08-11', accession_no='0000021344-95-000036')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q/A', filing_date='1995-08-11', accession_no='0000021344-95-000036')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1995-08-11', accession_no='0000021344-95-000033')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1995-05-11', accession_no='0000021344-95-000018')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1994-11-14', accession_no='0000021344-94-000031')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1994-08-10', accession_no='0000021344-94-000024')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-Q', filing_date='1994-05-06', accession_no='0000021344-94-000012')
No XBRL attachments found in filing Filing(company='COCA COLA CO', cik=21344, form='10-K', filing_date='1994-03-14', accession_no='0000950144-94-000600')

Yikes. One or more required columns are missing from the DataFrame.

Processing complete! Sample data:
label          net_sales  gross_margin    net_income  gross_margin_rate  \
date
2009-06-27  9.734000e+09  3.983000e+09  1.828000e+09          40.918430
2009-12-26  1.568300e+10  6.411000e+09  3.378000e+09          40.878658
2010-03-27  1.349900e+10  5.625000e+09  3.074000e+09          41.669753
2010-06-26  1.570000e+10  6.136000e+09  3.253000e+09          39.082803
2010-12-25  2.674100e+10  1.029800e+10  6.004000e+09          38.510153

label       net_margin_rate  bps_difference  dollar_difference ticker
date
2009-06-27        18.779536       22.138895       2.155000e+09   AAPL
2009-12-26        21.539246       19.339412       3.033000e+09   AAPL
2010-03-27        22.772057       18.897696       2.551000e+09   AAPL
2010-06-26        20.719745       18.363057       2.883000e+09   AAPL
2010-12-25        22.452414       16.057739       4.294000e+09   AAPL

In [21]:
all_calculated_margins[0]

for item in all_calculated_margins:
    print(item)

label          net_sales  gross_margin    net_income  gross_margin_rate  \
date
2009-06-27  9.734000e+09  3.983000e+09  1.828000e+09          40.918430
2009-12-26  1.568300e+10  6.411000e+09  3.378000e+09          40.878658
2010-03-27  1.349900e+10  5.625000e+09  3.074000e+09          41.669753
2010-06-26  1.570000e+10  6.136000e+09  3.253000e+09          39.082803
2010-12-25  2.674100e+10  1.029800e+10  6.004000e+09          38.510153
2011-03-26  2.466700e+10  1.021800e+10  5.987000e+09          41.423765
2011-06-25  2.857100e+10  1.192200e+10  7.308000e+09          41.727626
2011-12-31  4.633300e+10  2.070300e+10  1.306400e+10          44.683055
2012-03-31  3.918600e+10  1.856400e+10  1.162200e+10          47.374062
2012-06-30  3.502300e+10  1.499400e+10  8.824000e+09          42.811866
2012-12-29  5.451200e+10  2.106000e+10  1.307800e+10          38.633695
2013-03-30  4.360300e+10  1.634900e+10  9.547000e+09          37.495126
2013-06-29  3.532300e+10  1.302400e+10  6.900000e+09          36.871160
2013-12-28  5.759400e+10  2.184600e+10  1.307200e+10          37.931034
2014-03-29  4.564600e+10  1.794700e+10  1.022300e+10          39.317793
2014-06-28  3.743200e+10  1.473500e+10  7.748000e+09          39.364715
2014-12-27  7.459900e+10  2.974100e+10  1.802400e+10          39.867827
2015-03-28  5.801000e+10  2.365600e+10  1.356900e+10          40.779176
2015-06-27  4.960500e+10  1.968100e+10  1.067700e+10          39.675436
2015-12-26  7.587200e+10  3.042300e+10  1.836100e+10          40.097796
2016-03-26  5.055700e+10  1.992100e+10  1.051600e+10          39.403050
2016-06-25  4.235800e+10  1.610600e+10  7.796000e+09          38.023514
2016-12-31  7.835100e+10  3.017600e+10  1.789100e+10          38.513867
2017-04-01  5.289600e+10  2.059100e+10  1.102900e+10          38.927329
2017-07-01  4.540800e+10  1.748800e+10  8.717000e+09          38.513037
2017-12-30  8.829300e+10  3.391200e+10  2.006500e+10          38.408481
2018-03-31  6.113700e+10  2.342200e+10  1.382200e+10          38.310679
2018-06-30  5.326500e+10  2.042100e+10  1.151900e+10          38.338496
2018-12-29  8.431000e+10  3.203100e+10  1.996500e+10          37.991935
2019-03-30  5.801500e+10  2.182100e+10  1.156100e+10          37.612686
2019-06-29  5.380900e+10  2.022700e+10  1.004400e+10          37.590366
2019-12-28  9.181900e+10  3.521700e+10  2.223600e+10          38.354807
2020-03-28  5.831300e+10  2.237000e+10  1.124900e+10          38.361943
2020-06-27  5.968500e+10  2.268000e+10  1.125300e+10          37.999497
2020-12-26  1.114390e+11  4.432800e+10  2.875500e+10          39.777816
2021-03-27  8.958400e+10  3.807900e+10  2.363000e+10          42.506474
2021-06-26  8.143400e+10  3.525500e+10  2.174400e+10          43.292728
2021-12-25  1.239450e+11  5.424300e+10  3.463000e+10          43.763766
2022-03-26  9.727800e+10  4.255900e+10  2.501000e+10          43.749872
2022-06-25  8.295900e+10  3.588500e+10  1.944200e+10          43.256307
2022-12-31  1.171540e+11  5.033200e+10  2.999800e+10          42.962255
2023-04-01  9.483600e+10  4.197600e+10  2.416000e+10          44.261673
2023-07-01  8.179700e+10  3.641300e+10  1.988100e+10          44.516303
2023-12-30  1.195750e+11  5.485500e+10  3.391600e+10          45.874974
2024-03-30  9.075300e+10  4.227100e+10  2.363600e+10          46.578075
2024-06-29  8.577700e+10  3.967800e+10  2.144800e+10          46.257155
2024-12-28  1.243000e+11  5.827500e+10  3.633000e+10          46.882542
2025-03-29  9.535900e+10  4.486700e+10  2.478000e+10          47.050619
2025-06-28  9.403600e+10  4.371800e+10  2.343400e+10          46.490706
2025-12-27  1.437560e+11  6.923100e+10  4.209700e+10          48.158686
2026-03-28  1.111840e+11  5.478100e+10  2.957800e+10          49.270579

label       net_margin_rate  bps_difference  dollar_difference ticker
date
2009-06-27        18.779536       22.138895       2.155000e+09   AAPL
2009-12-26        21.539246       19.339412       3.033000e+09   AAPL
2010-03-27        22.772057       18.897696       2.551000e+09   AAPL
2010-06-26        20.719745       18.363057       2.883000e+09   AAPL
2010-12-25        22.452414       16.057739       4.294000e+09   AAPL
2011-03-26        24.271294       17.152471       4.231000e+09   AAPL
2011-06-25        25.578384       16.149242       4.614000e+09   AAPL
2011-12-31        28.195886       16.487169       7.639000e+09   AAPL
2012-03-31        29.658552       17.715511       6.942000e+09   AAPL
2012-06-30        25.194872       17.616995       6.170000e+09   AAPL
2012-12-29        23.991048       14.642647       7.982000e+09   AAPL
2013-03-30        21.895282       15.599844       6.802000e+09   AAPL
2013-06-29        19.534015       17.337146       6.124000e+09   AAPL
2013-12-28        22.696809       15.234226       8.774000e+09   AAPL
2014-03-29        22.396267       16.921527       7.724000e+09   AAPL
2014-06-28        20.698867       18.665847       6.987000e+09   AAPL
2014-12-27        24.161182       15.706645       1.171700e+10   AAPL
2015-03-28        23.390795       17.388381       1.008700e+10   AAPL
2015-06-27        21.524040       18.151396       9.004000e+09   AAPL
2015-12-26        24.199968       15.897828       1.206200e+10   AAPL
2016-03-26        20.800285       18.602765       9.405000e+09   AAPL
2016-06-25        18.405024       19.618490       8.310000e+09   AAPL
2016-12-31        22.834425       15.679443       1.228500e+10   AAPL
2017-04-01        20.850348       18.076981       9.562000e+09   AAPL
2017-07-01        19.197058       19.315980       8.771000e+09   AAPL
2017-12-30        22.725471       15.683010       1.384700e+10   AAPL
2018-03-31        22.608241       15.702439       9.600000e+09   AAPL
2018-06-30        21.625833       16.712663       8.902000e+09   AAPL
2018-12-29        23.680465       14.311470       1.206600e+10   AAPL
2019-03-30        19.927605       17.685081       1.026000e+10   AAPL
2019-06-29        18.666022       18.924344       1.018300e+10   AAPL
2019-12-28        24.217210       14.137597       1.298100e+10   AAPL
2020-03-28        19.290724       19.071219       1.112100e+10   AAPL
2020-06-27        18.853983       19.145514       1.142700e+10   AAPL
2020-12-26        25.803354       13.974461       1.557300e+10   AAPL
2021-03-27        26.377478       16.128996       1.444900e+10   AAPL
2021-06-26        26.701378       16.591350       1.351100e+10   AAPL
2021-12-25        27.939812       15.823954       1.961300e+10   AAPL
2022-03-26        25.709821       18.040050       1.754900e+10   AAPL
2022-06-25        23.435673       19.820634       1.644300e+10   AAPL
2022-12-31        25.605613       17.356642       2.033400e+10   AAPL
2023-04-01        25.475558       18.786115       1.781600e+10   AAPL
2023-07-01        24.305292       20.211010       1.653200e+10   AAPL
2023-12-30        28.363788       17.511185       2.093900e+10   AAPL
2024-03-30        26.044318       20.533756       1.863500e+10   AAPL
2024-06-29        25.004372       21.252783       1.823000e+10   AAPL
2024-12-28        29.227675       17.654867       2.194500e+10   AAPL
2025-03-29        25.986011       21.064608       2.008700e+10   AAPL
2025-06-28        24.920243       21.570462       2.028400e+10   AAPL
2025-12-27        29.283647       18.875038       2.713400e+10   AAPL
2026-03-28        26.602749       22.667830       2.520300e+10   AAPL

In [ ]:
# import matplotlib.pyplot as plt

# plt.figure(figsize=(20, 8))

# df_margins.plot(y='gross_margin', ax=plt.gca(), linewidth=2)
# plt.title('Gross Margin Evolution Across Financial Quarters', fontsize=16, fontweight='bold', pad=15)
# plt.xlabel('Report Date / Quarter', fontsize=12)
# plt.ylabel('Gross Margin Value', fontsize=12)
# plt.grid(True, linestyle='--', alpha=0.6) # Adds a light background grid
# plt.tight_layout()
# plt.show()

# df_margins.plot(y ='net_margin')